name: Generate Videos

on:
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - name: 🔧 Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            libssl-dev \
            libffi-dev \
            python3-dev \
            libasound2-dev \
            libasound2-plugins \
            libcurl4-openssl-dev \
            libpython3.10 \
            libpython3.10-dev \
            imagemagick \
            ffmpeg

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Python Packages
        run: pip install -r requirements.txt

      - name: Generate Videos
        env:
          AZURE_SPEECH_KEY: ${{ secrets.AZURE_SPEECH_KEY }}
          AZURE_REGION: ${{ secrets.AZURE_REGION }}
          PEXELS_API_KEY: ${{ secrets.PEXELS_API_KEY }}
        run: python video_generator.py

      - name: Upload Generated Videos
        uses: actions/upload-artifact@v4
        with:
          name: generated-output
          path: output/
