name: Upload to YouTube

on:
  workflow_run:
    workflows: ["Combine Videos"]
    types:
      - completed

jobs:
  upload:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - name: Download Combined Videos
        uses: actions/download-artifact@v4
        with:
          name: final-combined
          path: final_combined
      
      - name: Install Dependencies
        run: |
          pip install google-api-python-client google-auth-oauthlib

      - name: Restore YouTube Token
        env:
          GOOGLE_API_TOKEN_B64: ${{ secrets.YOUTUBE_TOKEN_B64 }}
        run: |
          echo "$GOOGLE_API_TOKEN_B64" | base64 -d > youtube_token.pickle

      - name: Install YouTube Dependencies
        run: pip install google-api-python-client google-auth-oauthlib

      - name: Upload to YouTube
        run: python upload_all_to_youtube.py

      - name: Clean Up Scenes JSON
        run: rm -f scenes/*.json
